<?php
//  ------------------------------------------------------------------------ //
// This is a module for Language Grid Toolbox. This provides access methods
// to the Language Grid.
// Copyright (C) 2009  NICT Language Grid Project
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//  ------------------------------------------------------------------------ //
$LANGRID_LANGUAGE_ARRAY = array(
	'ab' => 'Abkhazian',
	'aa' => 'Afar',
	'af' => 'Afrikaans',
	'ak' => 'Akan',
	'sq' => 'Albanian',
	'am' => 'Amharic',
	'ar' => 'Arabic',
	'an' => 'Aragonese',
	'hy' => 'Armenian',
	'as' => 'Assamese',
	'av' => 'Avaric',
	'ae' => 'Avestan',
	'ay' => 'Aymara',
	'az' => 'Azerbaijani',
	'bm' => 'Bambara',
	'ba' => 'Bashkir',
	'eu' => 'Basque',
	'bn' => 'Bengali',
	'dz' => 'Bhutani',
	'bh' => 'Bihari',
	'bi' => 'Bislama',
	'nb' => 'Bokmål, Norwegian',
	'bs' => 'Bosnian',
	'br' => 'Breton',
	'bg' => 'Bulgarian',
	'my' => 'Burmese',
	'be' => 'Byelorussian(Belarussian)',
	'km' => 'Cambodian',
	'ca' => 'Catalan',
	'ch' => 'Chamorro',
	'ce' => 'Chechen',
	'ny' => 'Chichewa',
	'zh-CN' => 'Chinese(Simplified)',
	'zh-TW' => 'Chinese(Traditional)',
	'zh' => 'Chinese',
	'cu' => 'Church Slavic',
	'cv' => 'Chuvash',
	'kw' => 'Cornish',
	'co' => 'Corsican',
	'cr' => 'Cree',
	'hr' => 'Croatian',
	'cs' => 'Czech',
	'da' => 'Danish',
	'dv' => 'Divehi',
	'nl' => 'Dutch',
	'en-GB' => 'English(United Kingdom)',
	'en-US' => 'English(United States)',
	'en' => 'English',
	'eo' => 'Esperanto',
	'et' => 'Estonian',
	'ee' => 'Ewe',
	'fo' => 'Faroese',
	'fj' => 'Fiji',
	'fi' => 'Finnish',
	'fr' => 'French',
	'fy' => 'Frisian',
	'ff' => 'Fulah',
	'gl' => 'Galician',
	'lg' => 'Ganda',
	'ka' => 'Georgian',
	'de' => 'German',
	'el' => 'Greek',
	'kl' => 'Greenlandic',
	'gn' => 'Guarani',
	'gu' => 'Gujarati',
	'ht' => 'Haitian',
	'ha' => 'Hausa',
//	'iw' => 'Hebrew',
	'he' => 'Hebrew',
	'hz' => 'Herero',
	'hi' => 'Hindi',
	'ho' => 'Hiri Motu',
	'hu' => 'Hungarian',
	'is' => 'Icelandic',
	'io' => 'Ido',
	'ig' => 'Igbo',
	'id' => 'Indonesian',
	'ia' => 'Interlingua',
	'ie' => 'Interlingue',
	'iu' => 'Inuktitut',
	'ik' => 'Inupiak',
	'ga' => 'Irish(Irish Gaelic)',
	'it' => 'Italian',
	'ja' => 'Japanese',
	'jv' => 'Javanese',
	'kn' => 'Kannada',
	'kr' => 'Kanuri',
	'ks' => 'Kashmiri',
	'kk' => 'Kazakh',
	'ki' => 'Kikuyu',
	'ky' => 'Kirghiz',
	'rn' => 'Kirundi',
	'rw' => 'Kiyarwanda',
	'kv' => 'Komi',
	'kg' => 'Kongo',
	'ko' => 'Korean',
	'kj' => 'Kuanyama',
	'ku' => 'Kurdish',
	'lo' => 'Laotian',
	'la' => 'Latin',
	'lv' => 'Latvian Lettish',
	'li' => 'Limburgan',
	'ln' => 'Lingala',
	'lt' => 'Lithuanian',
	'lu' => 'Luba-Katanga',
	'lb' => 'Luxemburgish',
	'mk' => 'Macedonian',
	'mg' => 'Malagasy',
	'ms' => 'Malay',
	'ml' => 'Malayalam',
	'mt' => 'Maltese',
	'gv' => 'Manx Gaelic',
	'mi' => 'Maori',
	'mr' => 'Marathi',
	'mh' => 'Marshallese',
	'mo' => 'Moldavian',
	'mn' => 'Mongolian',
	'na' => 'Nauru',
	'nv' => 'Navajo',
	'nd' => 'Ndebele, North',
	'nr' => 'Ndebele, South',
	'ng' => 'Ndonga',
	'ne' => 'Nepali',
	'se' => 'Northern Sámi',
	'nn' => 'Norwegian Nynorsk',
	'no' => 'Norwegian',
	'oc' => 'Occitan',
	'oj' => 'Ojibwa',
	'or' => 'Oriya',
	'om' => 'Oromo',
	'os' => 'Ossetian',
	'pi' => 'Pali',
	'ps' => 'Pashto',
	'fa' => 'Persian',
	'pl' => 'Polish',
	'pt-BR' => 'Portugese(Brazil)',
	'pt-PT' => 'Portugese(Portugal)',
	'pt' => 'Portuguese',
	'pa' => 'Punjabi',
	'qu' => 'Quechua',
	'rm' => 'Rhaeto-Romance',
	'ro' => 'Romanian',
	'ru' => 'Russian',
	'sm' => 'Samoan',
	'sg' => 'Sangho',
	'sa' => 'Sanskrit',
	'sc' => 'Sardinian',
	'gd' => 'Scots Gaelic(Scottish Gaelic)',
	'sr' => 'Serbian',
	'sh' => 'Serbo-Croatian',
	'st' => 'Sesotho',
	'tn' => 'Setswana',
	'sn' => 'Shona',
	'ii' => 'Sichuan Yi',
	'sd' => 'Sindhi',
	'si' => 'Singhalese',
	'ss' => 'Siswati',
	'sk' => 'Slovak',
	'sl' => 'Slovenian',
	'so' => 'Somali',
	'es' => 'Spanish',
	'su' => 'Sudanese',
	'sw' => 'Swahili',
	'sv' => 'Swedish',
	'tl' => 'Tagalog',
	'ty' => 'Tahitian',
	'tg' => 'Tajik',
	'ta' => 'Tamil',
	'tt' => 'Tatar',
	'te' => 'Telugu',
	'th' => 'Thai',
	'bo' => 'Tibetan',
	'ti' => 'Tigrinya',
	'to' => 'Tonga',
	'ts' => 'Tsonga',
	'tr' => 'Turkish',
	'tk' => 'Turkmen',
	'tw' => 'Twi',
	'ug' => 'Uigur',
	'uk' => 'Ukrainian',
	'ur' => 'Urdu',
	'uz' => 'Uzbek',
	've' => 'Venda',
	'vi' => 'Vietnamese',
	'vo' => 'Volapük',
	'wa' => 'Walloon',
	'cy' => 'Welsh',
	'wo' => 'Wolof',
	'xh' => 'Xhosa',
	'yi' => 'Yiddish',
	'yo' => 'Yorouba',
	'za' => 'Zhuang',
	'zu' => 'Zulu',
);
?>