<?php

$LOCALIZED_LANGUAGE_ARRAY = array(
	'sq' => 'Shqip', //Albanian
	'ar' => 'العربي', //Arabic
	'bg' => 'Български', //Bulgarian
	'ca' => 'Català', //Catalan
	'zh-CN' => '中文', //Chinese(CN)
	'hr' => 'Hrvatski', //Croatian
	'cs' => 'Čeština', //Czech
	'da' => 'Dansk', //Danish
	'nl' => 'Nederlands', //Dutch
	'en' => 'English',
	'et' => 'Eesti', //Estonian
	'fi' => 'Suomi', //Finnish
	'fr' => 'Français', //French
	'gl' => 'Galego', //Galician
	'de' => 'Deutsch', //German
	'el' => 'Ελληνικά', //Greek
	'iw' => 'עברי',//Hebrew
	'hi' => 'हिन्दी',//Hindi
	'hu' => 'Magyar', //Hungarian
	'id' => 'Bahasa Indonesia', //Indonesian
	'it' => 'Interlingua', //Italian
	'ja' => '日本語', //Japanese
	'ko' => '한국어', //Korean
	'lv' => 'Latviešu', //Latvian
	'lt' => 'Lietuvių', //Lithuanian
	'mt' => 'Malti', //Maltese
	'no' => 'Norsk', //Norwegian
	'pl' => 'Polski', //Polish
	'pt' => 'Português', //Portuguese
	'ro' => 'Română', //Romanian
	'ru' => 'Русский', //Russian
	'sr' => 'Српски', //Serbian
	'sk' => 'Slovenčina', //Slovak
	'sl' => 'Slovenščina', //Slovenian
	'es' => 'Español', //Spanish
	'sv' => 'Svenska', //Swedish
	'th' => 'ไทย', //Thai
	'tr' => 'Türkçe', //Turkish
	'uk' => 'Українська', //Ukrainian
	'vi' => 'Tiếng Việt', //Vietnamese
	'zh' => '中文', //Chinese
	'zh-TW' => 'Chinese(TW)',
	'tl' => 'Tagalog', //Tagalog
	'ur' => 'اردو', // Urdo
	'xh' => 'Xhosa', // Xhosa
	'za' => '壮語', // Vahcuengh
	'en-GB' => 'British English', // British English
	'aa' => 'Qafár af', // Afar
	'bm' => 'Bamanankan', // Bamanankan
	'ce' => 'Нохчийн мотт', // Chechen
	'ff' => 'Fula', // Fula
	'ht' => 'Krèyol ayisyen', // Haitian Creole
	'kj' => 'kuanyama', // kuanyama
);

?>