<?php
// $Id: xoops_version.php,v 1.4 2003/02/12 11:37:53 okazu Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;

$mydirname = basename( dirname( __FILE__ ) ) ;

$modversion['name'] = _MD_ALBM_FSHARE_NAME;
$modversion['version'] = 2.88 ; // = 2.90 - 0.02 (beta2)
$modversion['description'] = _MD_ALBM_FSHARE_DESC;
$modversion['author'] = "GIJ=CHECKMATE<br />PEAK Corp.(http://www.peak.ne.jp/)" ;
$modversion['credits'] = "Original: Daniel Branco<br />(http://bluetopia.homeip.net)<br />Kazumi Ono<br />(http://www.mywebaddons.com/)<br />The XOOPS Project" ;
$modversion['help'] = "" ;
$modversion['license'] = "GPL see LICENSE" ;
$modversion['official'] = 0;
$modversion['image'] = "images/filesharing_slogo.gif" ;
$modversion['dirname'] = $mydirname ;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/filesharing.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "filesharing_folder";
$modversion['tables'][1] = "filesharing_files";
//$modversion['tables'][2] = "filesharing_text";
//$modversion['tables'][3] = "filesharing_votedata";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
//$modversion['adminmenu'] = "admin/menu.php";

// Blocks
/*
$modversion['blocks'][1]['file'] = "filesharing_rfile.php";
$modversion['blocks'][1]['name'] = _MD_ALBM_BNAME_RANDOM;
$modversion['blocks'][1]['description'] = "Shows a random file";
$modversion['blocks'][1]['show_func'] = "b_filesharing_rfile_show";
$modversion['blocks'][1]['edit_func'] = "b_filesharing_rfile_edit";
$modversion['blocks'][1]['options'] = "$mydirname|140|1|0|1|60|1";
$modversion['blocks'][1]['template'] = "filesharing_block_rfile.html" ;
$modversion['blocks'][1]['can_clone'] = true ;

$modversion['blocks'][2]['file'] = "filesharing_topnews.php";
$modversion['blocks'][2]['name'] = _MD_ALBM_BNAME_RECENT;
$modversion['blocks'][2]['description'] = "Shows recently added files";
$modversion['blocks'][2]['show_func'] = "b_filesharing_topnews_show";
$modversion['blocks'][2]['edit_func'] = "b_filesharing_topnews_edit";
$modversion['blocks'][2]['options'] = "$mydirname|5|20|0|1||1";
$modversion['blocks'][2]['template'] = "filesharing_block_topnews.html" ;
$modversion['blocks'][2]['can_clone'] = true ;

$modversion['blocks'][3]['file'] = "filesharing_tophits.php";
$modversion['blocks'][3]['name'] = _MD_ALBM_BNAME_HITS;
$modversion['blocks'][3]['description'] = "Shows most viewed files";
$modversion['blocks'][3]['show_func'] = "b_filesharing_tophits_show";
$modversion['blocks'][3]['edit_func'] = "b_filesharing_tophits_edit";
$modversion['blocks'][3]['options'] = "$mydirname|5|20|0|1||1";
$modversion['blocks'][3]['template'] = "filesharing_block_tophits.html" ;
$modversion['blocks'][3]['can_clone'] = true ;

$modversion['blocks'][4]['file'] = "filesharing_topnews.php";
$modversion['blocks'][4]['name'] = _MD_ALBM_BNAME_RECENT_P;
$modversion['blocks'][4]['description'] = "Shows recently added files";
$modversion['blocks'][4]['show_func'] = "b_filesharing_topnews_show";
$modversion['blocks'][4]['edit_func'] = "b_filesharing_topnews_edit";
$modversion['blocks'][4]['options'] = "$mydirname|5|20|0|1||1";
$modversion['blocks'][4]['template'] = "filesharing_block_topnews_p.html" ;
$modversion['blocks'][4]['can_clone'] = true ;

$modversion['blocks'][5]['file'] = "filesharing_tophits.php";
$modversion['blocks'][5]['name'] = _MD_ALBM_BNAME_HITS_P;
$modversion['blocks'][5]['description'] = "Shows most viewed files";
$modversion['blocks'][5]['show_func'] = "b_filesharing_tophits_show";
$modversion['blocks'][5]['edit_func'] = "b_filesharing_tophits_edit";
$modversion['blocks'][5]['options'] = "$mydirname|5|20|0|1||1";
$modversion['blocks'][5]['template'] = "filesharing_block_tophits_p.html" ;
$modversion['blocks'][5]['can_clone'] = true ;
*/

// Menu
global $xoopsDB , $xoopsUser , $filesharing_catonsubmenu , $table_cat ;
$modversion['hasMain'] = 1 ;
$subcount = 1 ;
include dirname( __FILE__ ) . '/include/get_perms.php' ;
/*
if( $global_perms & 1 ) {	// GPERM_INSERTABLE
	$modversion['sub'][$subcount]['name'] = _MD_ALBM_TEXT_SMNAME1;
	$modversion['sub'][$subcount++]['url'] = "?page=submit";
	$modversion['sub'][$subcount]['name'] = _MD_ALBM_TEXT_SMNAME4;
	$modversion['sub'][$subcount++]['url'] = "?page=viewcat&uid=-1";
}
$modversion['sub'][$subcount]['name'] = _MD_ALBM_TEXT_SMNAME2;
$modversion['sub'][$subcount++]['url'] = "topten.php?hit=1";
if( $global_perms & 256 ) {	// GPERM_RATEVIEW
	$modversion['sub'][$subcount]['name'] = _MD_ALBM_TEXT_SMNAME3;
	$modversion['sub'][$subcount++]['url'] = "topten.php?rate=1";
}
if( isset( $filesharing_catonsubmenu ) && $filesharing_catonsubmenu ) {
	$crs = $xoopsDB->query( "SELECT cid, title FROM $table_cat WHERE pid=0 ORDER BY title") ;
	if( $crs !== false ) {
		while( list( $cid , $title ) = $xoopsDB->fetchRow( $crs ) ) {
			$modversion['sub'][$subcount]['name'] = " - $title" ;
			$modversion['sub'][$subcount++]['url'] = "?page=viewcat&cid=$cid" ;
		}
	}
}
*/

// Config
$modversion['config'][] = array(
	'name'			=> 'filesharing_filespath' ,
	'title'			=> '_MD_ALBM_CFG_FILESPATH' ,
	'description'	=> '_MD_ALBM_CFG_DESCFILESPATH' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'text' ,
	'default'		=> "/uploaded_files/data" ,
	'options'		=> array()
) ;
/*
$modversion['config'][] = array(
	'name'			=> 'filesharing_thumbspath' ,
	'title'			=> '_MD_ALBM_CFG_THUMBSPATH' ,
	'description'	=> '_MD_ALBM_CFG_DESCTHUMBSPATH' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'text' ,
	'default'		=> "/uploaded_files/icons" ,
	'options'		=> array()
) ;
$modversion['config'][] = array(
	'name'			=> 'filesharing_width' ,
	'title'			=> '_MD_ALBM_CFG_WIDTH' ,
	'description'	=> '_MD_ALBM_CFG_DESCWIDTH' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'int' ,
	'default'		=> '1024' ,
	'options'		=> array()
) ;
$modversion['config'][] = array(
	'name'			=> 'filesharing_height' ,
	'title'			=> '_MD_ALBM_CFG_HEIGHT' ,
	'description'	=> '_MD_ALBM_CFG_DESCHEIGHT' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'int' ,
	'default'		=> '1024' ,
	'options'		=> array()
) ;
*/
$modversion['config'][] = array(
	'name'			=> 'filesharing_fsize' ,
	'title'			=> '_MD_ALBM_CFG_FSIZE' ,
	'description'	=> '_MD_ALBM_CFG_DESCFSIZE' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'int' ,
	'default'		=> '10' ,
	'options'		=> array()
) ;
/*
$modversion['config'][] = array(
	'name'			=> 'filesharing_middlepixel' ,
	'title'			=> '_MD_ALBM_CFG_MIDDLEPIXEL' ,
	'description'	=> '_MD_ALBM_CFG_DESCMIDDLEPIXEL' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'text' ,
	'default'		=> '480x480' ,
	'options'		=> array()
) ;
*/
/*
$modversion['config'][] = array(
	'name'			=> 'filesharing_allownoimage' ,
	'title'			=> '_MD_ALBM_CFG_ALLOWNOIMAGE' ,
	'description'	=> '' ,
	'formtype'		=> 'yesno' ,
	'valuetype'		=> 'int' ,
	'default'		=> '1' ,
	'options'		=> array()
) ;
*/
/*
$modversion['config'][] = array(
	'name'			=> 'filesharing_makethumb' ,
	'title'			=> '_MD_ALBM_CFG_MAKETHUMB' ,
	'description'	=> '_MD_ALBM_CFG_DESCMAKETHUMB' ,
	'formtype'		=> 'yesno' ,
	'valuetype'		=> 'int' ,
	'default'		=> '0' ,
	'options'		=> array()
) ;
$modversion['config'][] = array(
	'name'			=> 'filesharing_thumbsize' ,
	'title'			=> '_MD_ALBM_CFG_THUMBSIZE' ,
	'description'	=> '' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'int' ,
	'default'		=> '140' ,
	'options'		=> array()
) ;
$modversion['config'][] = array(
	'name'			=> 'filesharing_thumbrule' ,
	'title'			=> '_MD_ALBM_CFG_THUMBRULE' ,
	'description'	=> '' ,
	'formtype'		=> 'select' ,
	'valuetype'		=> 'text' ,
	'default'		=> 'w' ,
	'options'		=> array(
		'_ALBUM_OPT_CALCFROMWIDTH' => 'w' , '_ALBUM_OPT_CALCFROMHEIGHT' => 'h' , '_ALBUM_OPT_CALCWHINSIDEBOX' => 'b' )
) ;
*/
/*
$modversion['config'][] = array(
	'name'			=> 'filesharing_popular' ,
	'title'			=> '_MD_ALBM_CFG_POPULAR' ,
	'description'	=> '' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'int' ,
	'default'		=> '100' ,
	'options'		=> array()
);
$modversion['config'][] = array(
	'name'			=> 'filesharing_newdays' ,
	'title'			=> '_MD_ALBM_CFG_NEWDAYS' ,
	'description'	=> '' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'int' ,
	'default'		=> '7' ,
	'options'		=> array()
) ;
$modversion['config'][] = array(
	'name'			=> 'filesharing_newfiles' ,
	'title'			=> '_MD_ALBM_CFG_NEWFILES' ,
	'description'	=> '' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'int' ,
	'default'		=> '8' ,
	'options'		=> array()
) ;
*/
$modversion['config'][] = array(
	'name'			=> 'filesharing_defaultorder' ,
	'title'			=> '_MD_ALBM_CFG_DEFAULTORDER' ,
	'description'	=> '' ,
	'formtype'		=> 'select' ,
	'valuetype'		=> 'text' ,
	'default'		=> 'dateD' ,
	'options'		=> array(
		"name ASC" => 'titleA' ,
		"description ASC" => 'descriptionA' ,
		"read ASC" => 'readA' ,
		"edit ASC" => 'editA' ,
		"date ASC" => 'dateA' ,
		"name DESC" => 'titleD' ,
		"description DESC" => 'descriptionD' ,
		"read DESC" => 'readD' ,
		"edit DESC" => 'editD' ,
		"date DESC" => 'dateD'
		)
	/*
	'options'		=> array(
		"file_id ASC" => 'lidA' ,
		"title ASC" => 'titleA' ,
		"date ASC" => 'dateA' ,
		"hits ASC" => 'hitsA' ,
		"rating ASC" => 'ratingA' ,
		"file_id DESC" => 'lidD' ,
		"title DESC" => 'titleD' ,
		"date DESC" => 'dateD' ,
		"hits DESC" => 'hitsD' ,
		"rating DESC" => 'ratingD'
		)
	*/
	) ;
$modversion['config'][] = array(
	'name'			=> 'filesharing_perpage' ,
	'title'			=> '_MD_ALBM_CFG_PERPAGE' ,
	//'description'	=> '_MD_ALBM_CFG_DESCPERPAGE' ,
	'description'	=> '',
	'formtype'		=> 'textbox' ,
	//'valuetype'		=> 'text' ,
	'valuetype'		=> 'int' ,
	//'default'		=> '10|20|50|100' ,
	'default'		=> '10' ,
	'options'		=> array()
) ;
/*
$modversion['config'][] = array(
	'name'			=> 'filesharing_addposts' ,
	'title'			=> '_MD_ALBM_CFG_ADDPOSTS' ,
	'description'	=> '_MD_ALBM_CFG_DESCADDPOSTS' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'int' ,
	'default'		=> '1' ,
	'options'		=> array()
) ;
*/
/*
$modversion['config'][] = array(
	'name'			=> 'filesharing_catonsubmenu' ,
	'title'			=> '_MD_ALBM_CFG_CATONSUBMENU' ,
	'description'	=> '' ,
	'formtype'		=> 'yesno' ,
	'valuetype'		=> 'int' ,
	'default'		=> '0' ,
	'options'		=> array()
) ;
*/
/*
$modversion['config'][] = array(
	'name'			=> 'filesharing_nameoruname' ,
	'title'			=> '_MD_ALBM_CFG_NAMEORUNAME' ,
	'description'	=> '_MD_ALBM_CFG_DESCNAMEORUNAME' ,
	'formtype'		=> 'select' ,
	'valuetype'		=> 'text' ,
	'default'		=> 'name' ,
	'options'		=> array('_MD_ALBM_OPT_USENAME'=>'name','_MD_ALBM_OPT_USEUNAME'=>'uname')
) ;
*/

/*
$modversion['config'][] = array(
	'name'			=> 'filesharing_viewcattype' ,
	'title'			=> '_MD_ALBM_CFG_VIEWCATTYPE' ,
	'description'	=> '' ,
	'formtype'		=> 'select' ,
	'valuetype'		=> 'text' ,
	'default'		=> 'list' ,
	'options'		=> array('_MD_ALBM_OPT_VIEWLIST'=>'list','_MD_ALBM_OPT_VIEWTABLE'=>'table')
) ;
$modversion['config'][] = array(
	'name'			=> 'filesharing_colsoftableview' ,
	'title'			=> '_MD_ALBM_CFG_COLSOFTABLEVIEW' ,
	'description'	=> '' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'int' ,
	'default'		=> '4' ,
	'options'		=> array()
) ;
$modversion['config'][] = array(
	'name'			=> 'filesharing_allowedexts' ,
	'title'			=> '_MD_ALBM_CFG_ALLOWEDEXTS' ,
	'description'	=> '_MD_ALBM_CFG_DESCALLOWEDEXTS' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'text' ,
	'default'		=> 'jpg|jpeg|gif|png' ,
	'options'		=> array()
) ;
$modversion['config'][] = array(
	'name'			=> 'filesharing_allowedmime' ,
	'title'			=> '_MD_ALBM_CFG_ALLOWEDMIME' ,
	'description'	=> '_MD_ALBM_CFG_DESCALLOWEDMIME' ,
	'formtype'		=> 'textbox' ,
	'valuetype'		=> 'text' ,
	'default'		=> 'image/gif|image/pjpeg|image/jpeg|image/x-png|image/png' ,
	'options'		=> array()
) ;
$modversion['config'][] = array(
	'name'			=> 'filesharing_usesiteimg' ,
	'title'			=> '_MD_ALBM_CFG_USESITEIMG' ,
	'description'	=> '_MD_ALBM_CFG_DESCUSESITEIMG' ,
	'formtype'		=> 'yesno' ,
	'valuetype'		=> 'int' ,
	'default'		=> '0' ,
	'options'		=> array()
) ;
*/
$modversion['config'][] = array(
	'name'			=> 'filesharing_rootedit' ,
	'title'			=> '_MD_ALBM_CFG_ROOT_EDIT' ,
	'description'	=> '' ,
	'formtype'		=> 'select' ,
	'valuetype'		=> 'int' ,
	'default'		=> '0' ,
	'options'		=> array(_MD_ALBM_OPT_EDIT_ADMIN => 0,_MD_ALBM_OPT_EDIT_ALL => 1)
) ;

// Search
$modversion['hasSearch'] = 0;
/*
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "filesharing_search";
*/

// Comments
$modversion['hasComments'] = 0;
/*
$modversion['comments']['itemName'] = 'lid';
$modversion['comments']['pageName'] = '?page=file';
// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'filesharing_comments_approve';
$modversion['comments']['callback']['update'] = 'filesharing_comments_update';
*/

// Templates
$modversion['templates'][1]['file'] = "filesharing_file.html" ;
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = "filesharing_viewcat_list.html" ;
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = "filesharing_viewcat_table.html" ;
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = "filesharing_index.html" ;
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = "filesharing_ratefile.html" ;
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = "filesharing_topten.html" ;
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = "filesharing_file_in_list.html" ;
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = "filesharing_header.html" ;
$modversion['templates'][8]['description'] = '';
$modversion['templates'][9]['file'] = "filesharing_footer.html" ;
$modversion['templates'][9]['description'] = '';
$modversion['templates'][10]['file'] = "filesharing_categories.html" ;
$modversion['templates'][10]['description'] = '';
$modversion['templates'][11]['file'] = "filesharing_imagemanager.html" ;
$modversion['templates'][11]['description'] = '';
$modversion['templates'][12]['file'] = "filesharing_base_top.html" ;
$modversion['templates'][12]['description'] = '';
$modversion['templates'][13]['file'] = "filesharing_base_footer.html" ;
$modversion['templates'][13]['description'] = '';
$modversion['templates'][14]['file'] = "filesharing_submit.html" ;
$modversion['templates'][14]['description'] = '';
$modversion['templates'][15]['file'] = "filesharing_editfile.html" ;
$modversion['templates'][15]['description'] = '';
$modversion['templates'][16]['file'] = "filesharing_delconf.html" ;
$modversion['templates'][16]['description'] = '';
$modversion['templates'][17]['file'] = "filesharing_createfolder.html" ;
$modversion['templates'][17]['description'] = '';
$modversion['templates'][18]['file'] = "filesharing_folderdelconf.html" ;
$modversion['templates'][18]['description'] = '';
$modversion['templates'][19]['file'] = "filesharing_multidelconf.html" ;
$modversion['templates'][19]['description'] = '';


//Install
$modversion['onInstall'] = "include/oninstall.inc.php";
//$modversion['onUpdate'] = 'onupdate.php' ;

// Notification
$modversion['hasNotification'] = 0;
/*
$modversion['notification']['lookup_file'] = 'include/notification.inc.php' ;
$modversion['notification']['lookup_func'] = "filesharing_notify_iteminfo" ;

$modversion['notification']['category'][1]['name'] = 'global';
$modversion['notification']['category'][1]['title'] = _MI_FSHARE_GLOBAL_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_FSHARE_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = array('index.php','?page=viewcat','?page=file');
$modversion['notification']['category'][2]['name'] = 'category';
$modversion['notification']['category'][2]['title'] = _MI_FSHARE_CATEGORY_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_FSHARE_CATEGORY_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = array('?page=viewcat','?page=file');
$modversion['notification']['category'][2]['item_name'] = 'cid';
$modversion['notification']['category'][2]['allow_bookmark'] = 1;

$modversion['notification']['category'][3]['name'] = 'file';
$modversion['notification']['category'][3]['title'] = _MI_FSHARE_FILE_NOTIFY;
$modversion['notification']['category'][3]['description'] = _MI_FSHARE_FILE_NOTIFYDSC;
$modversion['notification']['category'][3]['subscribe_from'] = array('?page=file');
$modversion['notification']['category'][3]['item_name'] = 'lid';
$modversion['notification']['category'][3]['allow_bookmark'] = 1;

$modversion['notification']['event'][1]['name'] = 'new_file';
$modversion['notification']['event'][1]['category'] = 'global';
$modversion['notification']['event'][1]['title'] = _MI_FSHARE_GLOBAL_NEWFILE_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_FSHARE_GLOBAL_NEWFILE_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_FSHARE_GLOBAL_NEWFILE_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'global_newfile_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_FSHARE_GLOBAL_NEWFILE_NOTIFYSBJ;

$modversion['notification']['event'][2]['name'] = 'new_file';
$modversion['notification']['event'][2]['category'] = 'category';
$modversion['notification']['event'][2]['title'] = _MI_FSHARE_CATEGORY_NEWFILE_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_FSHARE_CATEGORY_NEWFILE_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_FSHARE_CATEGORY_NEWFILE_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'category_newfile_notify';
$modversion['notification']['event'][2]['mail_subject'] = _MI_FSHARE_CATEGORY_NEWFILE_NOTIFYSBJ;
*/

$modversion['read_any'] = 1;

// On Install
if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'install_ok' && $_POST['module'] == $modversion['dirname'] ) {
	$_SESSION['filesharing_mydirname'] = $mydirname ; // store $mydirname in session
}

// On Update
if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok' && $_POST['dirname'] == $modversion['dirname'] ) {
	include dirname( __FILE__ ) . "/include/onupdate.inc.php" ;
}

?>